import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../../core/constants/app_colors.dart';
import '../../../../core/constants/app_sizes.dart';
import '../../../../core/theme/app_text_styles.dart';
import '../../../../core/widgets/glass_card.dart';
import '../../domain/entities/plan_step_entity.dart';
import '../bloc/plan_bloc.dart';
import '../bloc/plan_event.dart';
import '../bloc/plan_state.dart';

class PersonalizedPlanPage extends StatelessWidget {
  const PersonalizedPlanPage({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => PlanBloc()..add(const PlanStarted()),
      child: const _PlanView(),
    );
  }
}

class _PlanView extends StatelessWidget {
  const _PlanView();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: double.infinity,
        height: double.infinity,
        decoration: const BoxDecoration(gradient: AppColors.backgroundGradient),
        child: SafeArea(
          child: BlocBuilder<PlanBloc, PlanState>(
            builder: (context, state) {
              if (state.status == PlanStatus.loading) {
                return const Center(
                  child: CircularProgressIndicator(color: AppColors.goldAccent),
                );
              }

              return Padding(
                padding: const EdgeInsets.symmetric(
                  horizontal: AppSizes.screenPaddingH,
                ),
                child: Column(
                  children: [
                    const SizedBox(height: AppSizes.space8),
                    Row(
                      children: [
                        IconButton(
                          onPressed: () => Navigator.of(context).pop(),
                          icon: const Icon(
                            Icons.arrow_back_ios_new_rounded,
                            color: AppColors.primaryText,
                            size: 20,
                          ),
                        ),
                        Expanded(
                          child: Text(
                            'Your Money Plan',
                            textAlign: TextAlign.center,
                            style: AppTextStyles.h3,
                          ),
                        ),
                        const Icon(
                          Icons.auto_awesome_rounded,
                          color: AppColors.goldAccent,
                        ),
                      ],
                    ),

                    Expanded(
                      child: ListView(
                        children: [
                          const SizedBox(height: AppSizes.space16),
                          GlassCard(
                            borderColor: AppColors.goldAccent.withOpacity(0.5),
                            child: Row(
                              children: [
                                Container(
                                  width: 40,
                                  height: 40,
                                  decoration: BoxDecoration(
                                    shape: BoxShape.circle,
                                    color: AppColors.primaryPurple.withOpacity(
                                      0.4,
                                    ),
                                  ),
                                  child: const Icon(
                                    Icons.smart_toy_rounded,
                                    color: AppColors.info,
                                    size: 20,
                                  ),
                                ),
                                const SizedBox(width: AppSizes.space12),
                                Expanded(
                                  child: Column(
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    children: [
                                      Text(
                                        state.planTitle,
                                        style: AppTextStyles.bodyLarge.copyWith(
                                          color: AppColors.primaryText,
                                          fontWeight: FontWeight.w600,
                                        ),
                                      ),
                                      const SizedBox(height: 2),
                                      Text(
                                        'Generated by Money Buddy AI',
                                        style: AppTextStyles.caption,
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ),
                          const SizedBox(height: AppSizes.space24),

                          ...state.steps.map((s) => _PlanStepTile(step: s)),

                          const SizedBox(height: AppSizes.space24),
                        ],
                      ),
                    ),

                    SizedBox(
                      width: double.infinity,
                      child: ElevatedButton(
                        onPressed: () {
                          ScaffoldMessenger.of(context).showSnackBar(
                            const SnackBar(
                              content: Text(
                                'Plan started! Track your progress on Home.',
                              ),
                            ),
                          );
                          Navigator.of(context).pop();
                        },
                        child: const Text('Start This Plan'),
                      ),
                    ),
                    const SizedBox(height: AppSizes.space12),
                    TextButton.icon(
                      onPressed: () {
                        context.read<PlanBloc>().add(const PlanRegenerated());
                      },
                      icon: const Icon(Icons.refresh_rounded, size: 18),
                      label: const Text('Regenerate Plan'),
                    ),
                    const SizedBox(height: AppSizes.space24),
                  ],
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}

class _PlanStepTile extends StatelessWidget {
  final PlanStepEntity step;
  const _PlanStepTile({required this.step});

  @override
  Widget build(BuildContext context) {
    final bool isActive = step.status == PlanStepStatus.active;
    final bool isDone = step.status == PlanStepStatus.done;
    final double opacity = step.status == PlanStepStatus.upcoming ? 0.6 : 1.0;

    return Opacity(
      opacity: opacity,
      child: Padding(
        padding: const EdgeInsets.only(bottom: AppSizes.space16),
        child: IntrinsicHeight(
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Column(
                children: [
                  Container(
                    width: 32,
                    height: 32,
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: isDone
                          ? AppColors.successGreen
                          : (isActive
                                ? AppColors.goldAccent
                                : AppColors.darkPurple),
                      border: Border.all(
                        color: isActive
                            ? AppColors.goldAccent
                            : Colors.transparent,
                        width: 2,
                      ),
                    ),
                    child: Center(
                      child: isDone
                          ? const Icon(
                              Icons.check_rounded,
                              size: 16,
                              color: Colors.white,
                            )
                          : Text(
                              '${step.stepNumber}',
                              style: AppTextStyles.bodySmall.copyWith(
                                color: isActive
                                    ? AppColors.darkPurple
                                    : AppColors.secondaryText,
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                    ),
                  ),
                  if (step.stepNumber < 4)
                    Expanded(
                      child: Container(
                        width: 2,
                        margin: const EdgeInsets.symmetric(vertical: 4),
                        color: AppColors.goldAccent.withOpacity(0.3),
                      ),
                    ),
                ],
              ),
              const SizedBox(width: AppSizes.space12),
              Expanded(
                child: Padding(
                  padding: const EdgeInsets.only(bottom: AppSizes.space8),
                  child: Container(
                    padding: const EdgeInsets.all(AppSizes.space12),
                    decoration: BoxDecoration(
                      color: AppColors.glassCard,
                      borderRadius: BorderRadius.circular(AppSizes.cardRadius),
                      border: isActive
                          ? Border.all(
                              color: AppColors.goldAccent.withOpacity(0.5),
                            )
                          : null,
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(step.title, style: AppTextStyles.h3),
                        const SizedBox(height: 4),
                        Text(step.description, style: AppTextStyles.bodySmall),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
